packages/next-css/index.js
packages/next-css/package.json
yarn.lock

`next-css` only includes CSS that is imported for the index page of a project in production. @stephenmathieson put together an example project here which demonstrates the issue: https://github.com/stephenmathieson/next-plugins-css-bug
The crux of the issue is that `ExtractTextPlugin` should be creating multiple files (one for each entry), but when a static path is specified for the `filename` the output is always replaced with the last one. From the readme for [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin):
> ExtractTextPlugin generates a file per entry, so you must use [name], [id] or [contenthash] when using multiple entries.
Based on [this issue from the ExtractTextPlugin repo](https://github.com/webpack-contrib/extract-text-webpack-plugin/ …

Add support for multiple entry files to next-css

---

packages/next-css/readme.md
packages/next-less/readme.md
packages/next-sass/readme.md

The `<link ...>` tags need to be self-closing.

next-{css,less,sass}: fix README examples

---

packages/next-typescript/index.js

Fixes https://github.com/zeit/next.js/issues/3766
This enabled hot module replacement for typescript.

Add hot-self-accept-loader for typescript

---

packages/next-css/css-loader-config.js
packages/next-css/readme.md
packages/next-less/index.js
packages/next-less/readme.md
packages/next-sass/index.js
packages/next-sass/readme.md

This PR accompanies https://github.com/zeit/next-plugins/issues/15.
I can't find a way to pass options to the webpack css-loader, so this PR enables that. It should also work with `next-sass` (and other plugins relying on `next-css`).
In this update, `cssModules` accepts either a string or an object. 
If a **string**, behavior is as before (`modules` is set to the value of `cssModules`).
If an **object**, the `options` object is a join of default options and the user-specified `cssModules` object (with user-specified taking precedence).
Questions:
1) Would it be clearer to have a dedicated options argument, like `cssModulesOptions`? (I tried to make the API change as minimal as possible but maybe it's clearer as an additional argument).
2) In the example below, if a user neglects to …

Allow next-css to accept css-loader options

---

packages/next-sass/readme.md

The README file references `less` instead of `sass` in the examples

replace less references with sass

---

packages/next-css/css-loader-config.js
packages/next-css/index.js
packages/next-css/package.json
packages/next-css/readme.md
packages/next-less/index.js
packages/next-less/readme.md
packages/next-sass/index.js
packages/next-sass/readme.md
readme.md
yarn.lock

Fixes #25, #20 
:wave: FOUC when using next-css.
This adds https://github.com/sheerun/extracted-loader which works on the extracted stylesheet.
Thanks @sheerun for the loader :pray:

Add extracted-loader

---

packages/next-css/index.js
packages/next-less/index.js
packages/next-sass/index.js
yarn.lock

With https://github.com/zeit/next-plugins/pull/50, we now have a similar issue in development that we previously had in production where styles from multiple pages are not extracted properly to `/static/style.css`.
This updates the css, less, & sass plugins to also apply the `CommonsChunkConfig` changes in development (which is necessary now that we are always using the `ExtractTextPlugin`).

Move styles to commons chunk in development

---

packages/next-typescript/readme.md
readme.md

Add a note that alternative [`next-awesome-typescript` plugin](https://github.com/saitonakamura/next-awesome-typescript) is available

Note of `next-awesome-typescript` alternative

---

packages/next-css/commons-chunk-config.js

Added missing `main.js` conditional on commons chunk config. Without this generated css class names don't match up on build output.

Add missing `main.js` conditional 

---

packages/next-bundle-analyzer/index.js
packages/next-bundle-analyzer/readme.md

We would like to have this reported automatically to a static bucket somewhere so we can have it on a dashboard.
I thought the easiest way would be to allow extending the analyzer config, that could help other report in whatever way they want with the analyzer.

allow extending bundle analyzer config

---

readme.md

This PR contains similar to `next-preact` plugin for page rendering with very fast [Inferno](https://infernojs.org/) library. Now as community plugin 👌 
Also I set community plugin in alphabetical order.

Added 'next-inferno' to community plugins

---

packages/next-typescript/readme.md

Sorry, I made markdown syntax error in 'next-typescript' plugin's readme. This PR fixes it

 Fixed typo in 'next-typescript' plugin's readme

---

packages/next-preact/readme.md

Fix example server.js syntax error because of missing port variable definition

Add missing port

---

readme.md

This plugin allows exposing environment variables (using dotenv) to Next.js’s runtime configuration.
I made an example showing how it can be used: https://github.com/tusbar/next-runtime-dotenv/tree/master/example
Configuration is straightforward:
```js
const nextRuntimeDotenv = require('next-runtime-dotenv')
const withConfig = nextRuntimeDotenv({
// path: '.env'
public: [
'PUBLIC_VALUE'
],
server: [
'SERVER_ONLY'
]
})
module.exports = withConfig()
```
And it is used as such:
```js
import getConfig from 'next/config'
const {
publicRuntimeConfig: {PUBLIC_VALUE},
serverRuntimeConfig: {SERVER_ONLY}
} = getConfig()
export default () => {
console.log('PUBLIC_VALUE', PUBLIC_VALUE)
console.log('SERVER_ONLY', SERVER_ONLY)
return (
<div>
Open your console!
</div>
)
}
```

Add next-runtime-dotenv community plugin

---

packages/next-css/readme.md

It wasn't clear where to put this config file, so I suggest making it explicit by copying the language from the main repo.

Make it explicit where to put next.config.js

---

packages/next-typescript/index.js

Fixes #197
Depends on https://github.com/zeit/next.js/pull/4616/files

Only apply hot-self-accept-loader when on older versions of Next.js

---

packages/next-css/css-loader-config.js
packages/next-css/index.js
packages/next-css/readme.md
packages/next-less/index.js
packages/next-less/readme.md
packages/next-sass/index.js
packages/next-sass/readme.md
packages/next-stylus/index.js
packages/next-stylus/readme.md

Make it possible to pass postcss-loader options like config (path, context), parser, etc.
This can be useful, for example, to pass theme env variables to postcss-loader.
next.config.js would look like:
```
module.exports = withCSS({
postcssLoaderOptions: {
parser: true,
config: {
ctx: {
theme: JSON.stringify(process.env.REACT_APP_THEME)
}
}
}
})
```

Allow for postcss-loader options to be passed

---

packages/next-bundle-analyzer/readme.md

This line wasn't necessary for setting up this plugin. In fact, if you're requiring it here, you're likely rolling this plugin's behavior yourself.

Removed webpack bundle analyzer require from readme

---

readme.md

(next-purgecss)[https://github.com/lucleray/next-purgecss] can be used to remove unused styles.
It's mostly useful when using an external css library (like tachyons for example).

Add next-purgecss

---

packages/next-css/readme.md

Since Next.js will automatically add the css file to the HTML, we don’t need this code block anymore.

Remove obsolete _document.js

---

packages/next-typescript/package.json
yarn.lock

This is a follow-up to https://github.com/zeit/next-plugins/pull/236, which should close https://github.com/zeit/next-plugins/issues/227.
Context: https://github.com/zeit/next-plugins/pull/236#issuecomment-409945962

Upgrade @babel/preset-typescript to 7.0.0-rc.1

---

packages/next-workers/index.js
packages/next-workers/package.json
packages/next-workers/readme.md
readme.md

This makes it easier to implement Web Workers, as per [this issue](https://github.com/zeit/next.js/issues/4768).

Adding next-workers plugin to support Web Workers

---

readme.md

> Transpile untranspiled modules from your node_modules. Makes it easy to have local libraries and keep a slick, manageable dev experience.

Add next-plugin-transpile-modules community plugin

---

packages/next-typescript/readme.md

This changes the recommended tsconfig settings in the next-typescript
README. I'll also include this in the Next.js TS examples shortly.
- Enable `noEmit` to perform type-checking without transpiling
- `compileOnSave` is not required now that `noEmit` is required
- Upgraded `lib` from `es2016` to `es2017`

[@zeit/next-typescript] Updated recommended tsconfig in README

---

packages/next-typescript/readme.md

Hey, it's me again 🙃
As mentioned on https://github.com/zeit/next.js/pull/5267, this fixes `esModuleInterop` as discovered when updating the examples on the main repo.

[@zeit/next-typescript] esModuleInterop -> allowSyntheticDefaultImports

---

packages/next-workers/index.js
packages/next-workers/readme.md

This addresses this comment that the workers plugin is no longer working in next@7:
https://github.com/zeit/next-plugins/pull/218#issuecomment-428805318
This is rooted in this issue, in which the fix is to configure webpack to handle non-window global objects in the client in order for it to internally handle references to the global:
https://github.com/webpack/webpack/issues/6642
This next plugin is meant to handle files written as WebWorkers, in which `window` as the global is undefined (in lieu of `self`), so I've decided to explicitly fallback to `self` as the global object.
In addition, I've fixed a typo where a bracket was missing in the README.

fix workers plugin for nextjs@7 by handling global `self`

---

packages/next-css/css-loader-config.js
packages/next-css/package.json
yarn.lock

fixes https://github.com/zeit/next.js/issues/5152 and https://github.com/zeit/next.js/issues/5098 they're still in canary.
looks like use https://github.com/faceyspacey/extract-css-chunks-webpack-plugin is better with HMR.

[next-css] fix warnings about order and crash on hmr

---

packages/next-css/css-loader-config.js
packages/next-css/package.json

Related to this thread: https://spectrum.chat/thread/9f9f43b8-ec8b-45e5-a8e3-5b57a62e9e67

Minify CSS when mode is production

---

packages/next-css/css-loader-config.js

The option has been removed in version 1.0, see https://github.com/webpack-contrib/css-loader/pull/742/commits/965068d568cc4862c0a00b263fc5fea6840f72d2.
Fixes #286.

Don't pass removed `minimize` option to CSS Loader

---

packages/next-css/index.js

As previously this would lead to confusion.

Fail on user importing CSS in _document.js, since it won’t be bundled

---

packages/next-mdx/readme.md

The readme is lacking in that it talks about enabling other file extensions, but only shows how to keep the default. For people not used to regex it could be confusing how they can enable other extensions. 
Resolves #163

Show how to match other file extensions

---

readme.md

I have been maintaining next-fonts plugin available at https://github.com/rohanray/next-fonts . Can we add this to the list of community plugins. Thanks!

Adding next-fonts as a community plugin

---

packages/next-typescript/readme.md

The example `tsconfig.json` specifies the option: `"baseUrl": ".",`
This has two negative effects:
- TypeScript allows paths such as `import Component from "components/Component"` but Babel does not by default. Typical NextJS configurations don't allow paths like this, so this results in uncaught runtime errors.
- Typescript / VSCode's auto-import will use these invalid paths instead of relative paths.

Remove baseUrl config option.

---

readme.md

Since it's been removed from next (https://github.com/zeit/next.js/pull/6122), I think it makes sense to add next-size here as a community plugin.
I'll add a warning to the readme about the memory usage implications and I'll experiment some solutions to solve it in the community plugin itself, so next is safe 👌
some ideas :
- just showing the actual size and estimating the gzipped size (empirically)
- reading file on fs and calculating gzipped size (with a limit of nb of files)

Add next-size community plugin

---

packages/next-css/css-loader-config.js
packages/next-css/package.json

Yesterday was released css-loader 2.0 which use postcss 7 and and many changes to enhance performance.
Removed extracted-loader because forcing hot reload in extract-css-chunks-webpack-plugin works same.

Use css-loader 2.x

---

packages/next-css/readme.md
packages/next-less/readme.md
packages/next-mdx/readme.md
packages/next-preact/readme.md
packages/next-sass/readme.md
packages/next-stylus/readme.md
packages/next-typescript/readme.md
packages/next-workers/readme.md

This [tripped me up][tripped] while using [Next.js][next] for the first time.
I didn't understand that the `withSomething()` function had to wrap the configuration object.  
So I added an extra comment to each wrapper call to explicitly state that it should wrap the object.
```javascript
// next.config.js
module.exports = withSass({
/* config options here */
})
```
[tripped]: https://twitter.com/bradgarropy/status/1135570827318050817
[next]: https://nextjs.org

📝 documentation - more explicit wrapper examples

---

packages/next-workers/index.js

Always use globalObject:self for Worker contexts

---

packages/next-source-maps/readme.md

The example, provided in the readme didn't work properly because of an extra `()` next to the import.

Fix typo in documentation import

---

packages/next-preact/alias.js
packages/next-preact/index.js
packages/next-preact/package.json
packages/next-preact/preact-compat.js
packages/next-preact/readme.md

closes https://github.com/zeit/next-plugins/issues/493
closes https://github.com/zeit/next-plugins/issues/483
refs
- https://github.com/aomkirby123/nextjs-preactX
- https://github.com/kennykimjr/next-preactx-plugin
- https://github.com/FormidableLabs/react-ssr-prepass/issues/8#issuecomment-514128517

chore: Upgrade Preact

---

readme.md

Remove next-progressbar and next-size from readme since they have been both deprecated.

Remove next-progressbar and next-size from readme

---

packages/next-typescript/readme.md

The URL for the typescript documentation has been moved to https://nextjs.org/docs/basic-features/typescript

Update URL for documentation link for typescript
